### ISSUE TITLE
Bug report: first fetchRecord() fails with a PHP Warning

### ISSUE THREAD

**Issue by amestsantim** [gasparesganga/php-shapefile#19] opened 2019-09-23 05:57 UTC
After initializing an instance of ShapefileReader, when doing a fetchRecord() the first time, you get a PHP Warning and no record is returned. Subsequent calls to fetchRecord() seem to work.

"PHP Warning:  Declaration of Shapefile/Geometry/Polygon::addGeometry(Shapefile/Geometry/Linestring $Linestring) should be compatible with Shapefile/Geometry/GeometryCollection::addGeometry($Geometry) in /home/nahom/Projects/PWMDIS/pwmdis/vendor/gasparesganga/php-shapefile/src/Shapefile/Geometry/Polygon.php on line 50"

Steps to reproduce:

$Shapefile = new ShapefileReader('/path/to/file.shp', [
        Shapefile::OPTION_SUPPRESS_M => true,
        Shapefile::OPTION_SUPPRESS_Z => true,
]);
$Geometry = $Shapefile->fetchRecord()
PHP Warning: ...

I am using php-shapefile (v3.0.1) with Laravel 6.0.3, on Ubuntu 18.04, PHP 7.2.19

I don't know if it is related with the above error or not but ShapefileReader->__destruct() also throws off an exception (upon exit) 
"PHP Fatal error:  Uncaught ErrorException: fclose() expects parameter 1 to be resource, integer given in /path/to/gasparesganga/php-shapefile/src/Shapefile/Shapefile.php:523"

I have attached one sample shapefile (zip) that produces the error.

[sample_shapefile.zip](https://github.com/gasparesganga/php-shapefile/files/3640846/sample_shapefile.zip)

**Comment by gasparesganga** [comment] 2019-09-23 08:50
It seems we've got 2 different things here:

1) The PHP Warning *Declaration of X must be compatible with Y* is something trivial I am fixing right now. It was due to some final touches I introduced right before releasing the refactored code (it used to throw an E_STRICT in previous versions of PHP). It has **nothing** to do with *calling fetchRecord() the first time* of course. A bugfix release is already on its way.

2) I could not reproduce the Fatal Error, which is self explanatory. I could open, read and close those shapefiles just fine. Are you manually passing the resources to the library and maybe closing them on your own?

**IMPORTANT: I am commiting a fix to the first problem identified here, effectively closing this issue. Please test your code against upcoming 3.0.2 version and in case you still get any error, open a new issue for that.**

**Closed as completed** 2019-09-23 08:55 UTC

**Comment by amestsantim** [comment] 2019-09-23 13:51
Yes, version 3.0.2 has fixed the issue.

Thank you for the very prompt response and action.

The second error is caused when I exit after having initialized the ShapefileReader class on a tinker (laravel/tinker package) command line.
I think the file handles are being automatically closed before being closed in the closeFile() method of the Shapefile class
I think it would be safer if you replaced line 522, 
fclose($handle); 
with
if(is_resource($handle)) fclose($handle);

**Comment by gasparesganga** [comment] 2019-09-23 14:23
This behaviour is interesting indeed. I am not familiar with tinker nor laravel, thus I cannot test it myself.
It actually used to be like the version you proposed (checking if the handles were actually resources) but in the end I decided to drop the check to promote *clean code* writing on users side.

Would you make a test and tell me if you still get the same error please?
Try to set the ShapefileReader instance to `null` **before** exiting in your code:
`$ShapefileReader = null;`

Does it still yeld the fatal error?

**Comment by amestsantim** [comment] 2019-09-23 14:49
Just tested it by setting the reader instance to null before exiting and the fatal error has disappeared!

![Screenshot from 2019-09-23 17-50-01](https://user-images.githubusercontent.com/8392160/65436688-2fe4e200-de2b-11e9-96a4-b0a4ea9c4693.png)

**Comment by gasparesganga** [comment] 2019-09-23 15:25
Yep, that's what I was talking about before ;)

Of course in most situations (PHP used in conjuction with Apache) setting a ShapefileReader instance to `null` is redundant, but having full control of the code flow and especially resource handles is very important in my opinion.
So I guess I'll simply leave it as is, since it is effectively *promoting best practices*, isn't it?

By the way, thank you for your feedback!

**Comment by amestsantim** [comment] 2019-09-24 04:49
Yes, I suppose you are right.
Thank you!
I'd like to help out. If there are specific tasks you'd like handled, please let me know.
As I use laravel a lot, I tried to answer a question in the comments regarding that...
I was also wondering if you had any plans for reading and returning the current srid of the shapefile.
I know getWKT() returns the raw contents of the .prj file. I was looking at the specs of .prj files, if there is a simple way of parsing it and getting the srid from it, please let me know and I'd be happy to contribute some code that does that as I think that would be useful.
Thanks again!
Nahom

**Comment by gasparesganga** [comment] 2019-09-24 07:31
Yep, I saw that comment about integrating it with Laravel. thanks.

About the PRJ, thank you for your availibility, unfortunately the format of PRJ files that come with Shapefiles does not *usually* contain a straight EPSG code... it is a little more complicated (thought possible) to guess it analyzing the file, but it is a different task than the purpose of this library (*reading and writing Shapefiles*).
Also, we shouldn't forget that a PRJ definition can be *custom*, hence it would not exist an official EPSG code for that (a large amount of Shapefiles I work with are like that actually, using some local cassini projection), making things even more complicated.
I looked into that in the past, but ultimately decided that the best option is to leave this to the user, who can get advantage of some online services or write his own code to parse it according to the specific use case.

**Comment by amestsantim** [comment] 2019-09-24 07:47
Alright then, in that case, do you have a recommendation for finding the CRS of a given file?
In my application, I have an "Import" feature where a user supplies the shapefiles and I use your library to read them and store the "features" in postgres/postgis and they are later displayed on a map. As you know, displaying them on a map will require transforming them to a suitable CRS (4326).
Transforming is simple enough using postgis but then you'd need to know the origin srid.
What would be the best way to achieve this?

**Comment by gasparesganga** [comment] 2019-09-24 09:38
Originally this library was born for this exact purpose (importing shapefiles into PostGIS using PHP), hence the WKT support from the very first release ;)

There are a few online and offline tools to *convert* WKT projections strings to proj.4 (just search for "wkt to proj4" on google), but probably since you are already using PostGIS you'd better rely on one of its dependecies, **gdal**, which will convert WKT to proj.4 for you (again, plenty of examples online).

**EDIT:** Now, the least you can do is starring this library! ehehehehe :))

**Comment by amestsantim** [comment] 2019-09-24 10:44
proj4php looks ok. I'm going to give it a go.
Starring the repo is the least I can do!
Thank you!

**Comment by gasparesganga** [comment] 2019-09-24 11:17
Thank you! ;)
