### ISSUE TITLE
Uppercasing (bug)

### ISSUE THREAD

**Issue by pablodegrande** [gasparesganga/php-shapefile#22] opened 2019-10-11 21:58 UTC
If you do not force the fieldnames to uppercase, and add fields names like 'id', when you then make setData it throws exception because it cannot find the field. If you change id for ID the problem dissapears.

**Comment by gasparesganga** [comment] 2019-10-12 10:05
I cannot reproduce this or I don't really get it, could you provide some example code?
To me it looks like it's doing what it is expected to do at the moment, or maybe *what I expect it to do* is not the most intuitive thing?

**Comment by pablodegrande** [comment] 2019-10-13 13:27
Following code throws "Exception: ShapefileException > Geometry is missing a field defined in the Shapefile", where the name of the missing field inside the library is "ID_COL". 

    $Shapefile = new ShapefileWriter($shapeFile, [Shapefile::OPTION_OVERWRITE_EXISTING_FILES  => true]);
		$Shapefile->setPRJ(self::PRJ);
		$Shapefile->setShapeType(Shapefile::SHAPE_TYPE_POINT);
		$Shapefile->addCharField('id_col', 10);
		$geom = new Point(1, 1);
		$geom->setData('id_col', 'c');
		$Shapefile->writeRecord($geom);
		$Shapefile = null;
		
The default upper casing is active for field names, but then it is not upper casing the set data argument. I would expected: 
1) 'make all fields uppercase' would lead to some sort of case insensitivity. 
2) Or setData could throw a field not found exception... what would force to strupper in user code for set data... 

I think that if you hide the strupper for field creating, it would make sense to hide it too for set data.... so I'd prefer option 1).

**Comment by gasparesganga** [comment] 2019-10-13 13:59
Alright now I get it. And this is actually ***the intended behaviour by design***...
In regards to your possible scenarios:
1) Forcing every field name passed to `setData()` through sanitization could lead to some very nasty hidden bugs: sanitization is not just about uppercasing strings, but also truncating too long ones and replacing illegal characters (and once the request about #23

**Comment by gasparesganga** [comment] 2019-10-13 14:19
Alright now I get it. And this is actually ***the intended behaviour by design***...
In regards to your possible scenarios:

1) Forcing every field name passed to `setData()` through sanitization could lead to some very nasty hidden bugs: sanitization is not just about uppercasing strings, but also truncating too long ones and replacing illegal characters (and once the request #23 about duplicate names is addressed, it will be even worse), thus imagine what kind of unexpected result might arise if a user passes
`$geom->setData('description_xxx', 'xxx');`
`$geom->setData('description_yyy', 'yyy');`
Both `description_xxx` and `description_yyy` would be silently converted to `DESCRIPTIO`, and just the last `yyy` value would be assigned to the field. I agree a programmer should pay attention to those details, but I don't want to deploy code that might encourage bad practices.

2) `Geometry` objects cannot know anything about fields definition until they are added to a `Shapefile` (not without creating circular references). This is also by design and I think there's nothing wrong in having a large set of data available in a `Geometry` whose get used just partially by a `Shapefile`: other fields could eventualy be used by another `Shapefile`, nothing prevents you from adding the same `Geometry` to different `Shapefiles`...

This is also one of the reasons all `ShapefileWriter` field-adding methods return the sanitized name: probably the best way to deal with it is to *map* sanitized field names outside the library. Something like that (well, that's just the idea):
```
$fields['id_col'] = $Shapefile->addNumericFieldField('id_col', 10);
$fields['description'] = $Shapefile->addCharField('description', 50);
...
...
$geom->setData($fields['id_col'], 1);
$geom->setData($fields['description'], 'some description here');
```
Of course something like that would become even more important once #23 becomes effective.
My feeling is that field names mapping strategy should be left up to the user.

**EDIT**: Sorry, my mouse slipped to *close issue*, had to reopen it!

**Comment by pablodegrande** [comment] 2019-10-13 14:24
I guess you are mixing sanitize with uppercasing. From an API/library user perspective, they are separated flags. So, we shouldn't be talking about sanitize in the issue. It's just a case-sensitivity thing.

By the way, about santize, when I inspected a bit the code yesterday, I think maybe the concept of satinize is taken a bit too far... e.g. when you receive a coordinate, I guess it would a enough check if its a number. If it's not, then throw an exception. We replace non number chars under a sanitizenumber function is a bit odd, and time consuming (creates a new string for every received string).

**Comment by gasparesganga** [comment] 2019-10-13 14:34
Gosh you are right! I completely forgot the `OPTION_DBF_FORCE_ALL_CAPS` option! :))
In my defense, I have been working on many different things since the last release...

Sure, that's the right thing to do, uppercasing field names when coupling Geometries to Shapefiles in case `OPTION_DBF_FORCE_ALL_CAPS` is on!

**Closed as completed** 2019-10-13 15:18 UTC
Labels: bug, next release
